### ISSUE TITLE
Support for focal release

### ISSUE THREAD

**Issue by prateekkish** [frenkel/hfl#17]
[SOLVED]
Currently, there's a dependency on libffi6 which has been moved to libffi7 in the focal releases of Ubuntu.

Could someone rebuild the bundle that can work with Ubuntu 19+?

**Comment by frenkel** [comment]
The .deb works for us on Ubuntu 19.10 and Ubuntu 20.04. What is it that you're trying to achieve? What is the error message?

**Comment by prateekkish** [comment]
Steps:
1. Downloaded `ubuntu-timer-for-harvest_0.3.2_amd64.deb` from latest release.
2. `sudo dpkg -i ubuntu-timer-for-harvest_0.3.2_amd64.deb `

Errors:
```
Selecting previously unselected package timer-for-harvest.
(Reading database ... 188459 files and directories currently installed.)
Preparing to unpack ubuntu-timer-for-harvest_0.3.2_amd64.deb ...
Unpacking timer-for-harvest (0.3.2) ...
dpkg: dependency problems prevent configuration of timer-for-harvest:
 timer-for-harvest depends on libffi6 (>= 3.2.1); however:
  Package libffi6 is not installed.

dpkg: error processing package timer-for-harvest (--install):
 dependency problems - leaving unconfigured
Processing triggers for gnome-menus (3.36.0-1ubuntu1) ...
Processing triggers for desktop-file-utils (0.24-1ubuntu3) ...
Processing triggers for mime-support (3.64ubuntu1) ...
Errors were encountered while processing:
 timer-for-harvest
```

My earlier comment about Ubuntu 20 having `libffi7` was based on [this comment](https://www.reddit.com/r/Ubuntu/comments/g8b21o/cant_install_a_package_unmet_dependences/)

**Comment by frenkel** [comment]
Our 20.04 install was an upgrade from 19.10, that's probably why it did have libffi6. I've build a Debian package for 20.04 now as well. The [latest release](https://github.com/frenkel/timer-for-harvest/releases/tag/v0.3.2) has been updated.
Don't hesitate to ask when something still doesn't work.

**Comment by prateekkish** [comment]
@frenkel Thanks for the prompt response.
