### ISSUE TITLE
Feature Request: Show client in project-list

### ISSUE THREAD

**Issue by jarnalyrkar** [frenkel/hfl#19]
Is there a way to display the client also in the project-dropdown? The company I work at have very many projects with the same name but different clients. 

I installed rust and cloned the project to give it a try, but I have never touched rust before, and anything I tried to hack together only returned errors, which was kind of expected :)

**Comment by frenkel** [comment]
We have the same problem. Unfortunately the API of Harvest only lists the info you see how for all your project assignments. It should still be possible with an extra API call, but that is the reason I haven’t build it yet.
I’ll give this a try in a few weeks time.

**Comment by frenkel** [comment]
I'm planning to have a look at this next weekend. Sorry for the delay.

**Comment by frenkel** [comment]
This has been added to v0.3.3 that will be published in a few minutes.
