### ISSUE TITLE
Refresh entries automatically

### ISSUE THREAD

**Issue by Flimm** [frenkel/hfl#21]
If you use Harvest on another device or through the web interface, the Time Tracker app does not notice new changes, you have to press F5 manually.

Could the app refresh itself automatically?

**Comment by frenkel** [comment]
I understand the problem. What kind of refresh rate would you consider appropriate?
Frrom a technical viewpoint I don’t think it is wise to automatically refresh every minute. If all clients refresh every minute it would cause a lot of load on the Harvest servers.

**Comment by Flimm** [comment]
Fair enough. How about automatically refreshing when the user focusses the window?

**Comment by frenkel** [comment]
Great idea! I'll test whether this is workable in a few weeks. It might cause irritation for other users because it will incur some waiting time while the request is completed. If it's to slow I could also make it configurable.

**Comment by frenkel** [comment]
Your idea seems to work quite fine, thanks again. I've implemented it in master and am planning to build a new release this weekend. You can give it a go earlier by cloning the repo and running `cargo run` if you have installed cargo/rust. The build takes quite some time, but it should work out of the box.

**Comment by frenkel** [comment]
This has been added to v0.3.3 that will be published in a few minutes.

**Comment by Flimm** [comment]
Yay! It seems to work well. Thank you.
