### ISSUE TITLE
Feature Request

### ISSUE THREAD

**Issue by davedew** [frenkel/hfl#26]
Love where this is going!  Not really an issue, just a feature request.  I'd help build this if I had the time and GTK knowledge base.  Would love to see the app minimize to tray: [https://github.com/ubuntu/gnome-shell-extension-appindicator](https://github.com/ubuntu/gnome-shell-extension-appindicator)

A click from tray would show the timers with the ability to start, stop, etc.  The official Harvest app on Mac is what I'm referencing.  Its very handy.

**Comment by frenkel** [comment]
Thank you! Great idea, but I won't be able to add this. I like vanilla GNOME and that doesn't have a tray with icons. I find it difficult to build and maintain features that I don't use on a daily basis. Anybody that can add this is free to open a PR of course!
