### ISSUE TITLE
Add package for Ubuntu 20.10

### ISSUE THREAD

**Issue by astme** [frenkel/hfl#28]
I tried to install `ubuntu-20.04-timer-for-harvest_0.3.3_amd64.deb` on ubuntu 20.10 and it failed with an error:
```
The following packages have unmet dependencies:
 timer-for-harvest : Depends: libffi7 (>= 3.3) but it is not installable
E: Unable to correct problems, you have held broken packages.
```
Could you please also provide release for ubuntu 20.10, or give me some guidelines how can install it?

**Comment by frenkel** [comment]
Sure, I've updated the release: https://github.com/frenkel/timer-for-harvest/releases/tag/v0.3.3
