### ISSUE TITLE
Projects & Tasks autocompletion

### ISSUE THREAD

**Issue by iatanas0v** [frenkel/hfl#29]
Right now you have to open the projects dropdown to select the project (same applies to tasks). I have long list of projects available and it can be hard to spot the project sometimes.

It would be great if you can focus the field and start typing, some fuzzy match to occur and to show you suggestions.

If you like the idea, I can try to work on this one, but I'll need a bit of guidence, because I've never done GTK or Rust development.

**Comment by frenkel** [comment]
Thanks for your suggestion! What version are you using? This should already work. Click in the projects dropdown and start typing to filter the results.

**Comment by iatanas0v** [comment]
I'm running the lastest version 0.3.3. 

You're dead right that the autocomplete is there :sweat_smile: but I didn't notice it because of another issue. In few words, the autocomplete is not shown (or at least not on screen, I guess) if you have two monitors, you're running the application on the right one and you're running under wayland (this must be the culprit).

Things I tried:

1. [Xorg] - works on any monitor
2. [Wayland][2 monitors] - works only on the left one.
3. [Wayland][1 monitor] - no issues there

I'd guess some absolute positioning is going on for the autocomplete dropdown and because wayland and xorg have different approach to coordinates something goes south.

Here's a short video illustrating the issue:

https://user-images.githubusercontent.com/4757057/104595583-78a55780-567b-11eb-8e7a-6adeebdbe5ba.mp4

**Comment by frenkel** [comment]
Ah, that explains! I had the same issue in GNOME settings and switched back to Xorg because of it. I don't know how to fix it unfortunately. Any ideas?

**Comment by iatanas0v** [comment]
I'll do some research in the upcoming days when I have some free time.

**Comment by iatanas0v** [comment]
So this is a bug in GTK itself. I guess, the best bet is to wait until it's resolved upstream:

* https://gitlab.gnome.org/GNOME/gtk/-/issues/2794
* https://gitlab.gnome.org/GNOME/gtk/-/merge_requests/2681

**Comment by frenkel** [comment]
That's unfortunate. I'll close this one then.
