### ISSUE TITLE
3.4 Ubuntu 20.10 libffi6 Dependancy

### ISSUE THREAD

**Issue by davedew** [frenkel/hfl#31]
Getting this on 20.10:

The following packages have unmet dependencies: timer-for-harvest: Depends: libffi6 (>= 3.2.1) but it is not installable

libffi6 package is also not directly installable via apt install.

**Comment by frenkel** [comment]
Is this using the ubuntu-20.10-timer-for-harvest*deb package? Or did you by accident try the 20.04 package?

**Comment by davedew** [comment]
Yes, its using the ubuntu-20.10-timer-for-harvest_0.3.4_amd64.deb file.  I was able to install 0.3.3 again without an issue.

**Comment by frenkel** [comment]
Could you try the file ubuntu-20.04-timer-for-harvest_0.3.4_amd64.deb? I believe is swapped the file names :see_no_evil:

**Comment by davedew** [comment]
I received this message:

The following packages have unmet dependencies:
  timer-for-harvest: Depends: libffi7 (>= 3.3) but it is not installable

Looks like the version on libffi went up one on the 20.04 file.

**Comment by frenkel** [comment]
Sorry for the mess, I found the cause: I swapped the Ubuntu 20.10 and Debian 10 filenames. I've updated the release files and they should now install fine. Let me know if you experience any other problems.

**Comment by davedew** [comment]
That worked, thanks!!  Your work is appreciated!
