### ISSUE TITLE
v0.3.5 on Ubuntu 20.04

### ISSUE THREAD

**Issue by MrPrimate** [frenkel/hfl#33]
Loving the tool, I just tried to upgrade and I'm getting the following on Ubuntu 20.04:
```
sudo dpkg -i ~/Downloads/ubuntu-20.04-timer-for-harvest_0.3.5_amd64.deb
(Reading database ... 557832 files and directories currently installed.)
Preparing to unpack .../ubuntu-20.04-timer-for-harvest_0.3.5_amd64.deb ...
Unpacking timer-for-harvest (0.3.5) over (0.3.4) ...
dpkg: dependency problems prevent configuration of timer-for-harvest:
 timer-for-harvest depends on libglib2.0-0 (>= 2.64.6); however:
  Version of libglib2.0-0:amd64 on system is 2.64.3-1~ubuntu20.04.1.

dpkg: error processing package timer-for-harvest (--install):
 dependency problems - leaving unconfigured
Processing triggers for desktop-file-utils (0.24-1ubuntu3) ...
Processing triggers for gnome-menus (3.36.0-1ubuntu1) ...
Processing triggers for mime-support (3.64ubuntu1) ...
Errors were encountered while processing:
 timer-for-harvest
 ```

**Comment by frenkel** [comment]
I don't understand how I keep switching the debian package names. Could you try whether the ubuntu-20.10 package or the debian-10 package does work? I think one of those is actually the one for ubuntu-20.04.

**Comment by frenkel** [comment]
It seems like 2.64.6 is part of focal-updates. Did you run `apt update` and `apt dist-upgrade` before installation? Do you have the updates repo enabled? Ubuntu should install that version on your system then.
https://packages.ubuntu.com/search?keywords=libglib2&searchon=names&suite=focal-updates&section=all

**Comment by MrPrimate** [comment]
🙇🏻 Apologies this does indeed seem to be the case.

**Comment by frenkel** [comment]
No problem, happy to help and glad you like the product 😀
