### ISSUE TITLE
Speedup UX of 'Add time entry'

### ISSUE THREAD

**Issue by wvengen** [frenkel/hfl#34]
First of all, thanks for this great little app! :)

I've got a suggestion to make the UX a little faster. When adding a new item (`+` button), one always needs to choose a project and a task. This requires pressing the down arrow twice. I think this could be improved.

The initial view of the dialog 'Add time entry' would show the list of all projects by default, requiring only one click to select.
When a project is selected, a list of all project tasks is shown, requiring only one click to select.
I think it would be useful to have the note field always visible, because one may want to write some notes first, then ponder what project and task belong to it.

**Comment by frenkel** [comment]
Thank you!

I don't think I understand your proposal. Could you create some sketches? For example by drawing on this screenshot:
![Popup](https://raw.githubusercontent.com/frenkel/timer-for-harvest/master/assets/popup.png?raw=true "The time entry popup") or by showing some other GNOME applications that contain interface components similar to what you propose.

I use it with a list of ~250 projects so showing them all at once is not an option for everybody, but maybe I'm misunderstanding you.

**Comment by wvengen** [comment]
Thanks for your quick response, I will try to do so and come up with some examples.
Indeed it needs to work with both long and short project lists.

**Comment by wvengen** [comment]
One idea:
![mockup](https://user-images.githubusercontent.com/503804/109817358-253e9700-7c32-11eb-839c-d13626baa5b0.png)

When the dialog appears, the focus is on the project search box, where you can start typing (or use the arrows) (enter selects).
After pressing enter, the project selector closes and the tasks box is expanded, where you can start typing (ibid).
After pressing enter, you go to the notes box (then tab to other fields, as normal).

Another idea is more a wizard-like interface:
![mockup2](https://user-images.githubusercontent.com/503804/109818415-3e941300-7c33-11eb-9932-21d26c9fe8dc.png)

This probably needs some iterations to be more polished, but I hope the idea is clearer now.

**Comment by frenkel** [comment]
Great, thank you. I see what you mean now. Do you know of any GNOME or GTK applications that use a pattern similar to this?

**Comment by wvengen** [comment]
Hmmm ... maybe Gnome Todo?
![image](https://user-images.githubusercontent.com/503804/109821702-8c5e4a80-7c36-11eb-84e8-6acfd47f48ca.png)

This image may also provide inspiration (same app)
![image](https://user-images.githubusercontent.com/503804/109822049-e3641f80-7c36-11eb-8d2c-6f695f928eda.png)

Gnome settings has a scrolling list (but without search)
![image](https://user-images.githubusercontent.com/503804/109821919-c16a9d00-7c36-11eb-927d-43110950ccab.png)

Gnome Software comes to mind
![image](https://user-images.githubusercontent.com/503804/109822172-0098ee00-7c37-11eb-91ba-a6eb490390c6.png)

Tasks could even be grouped under a project with a treeview like [explained on SO](https://stackoverflow.com/questions/56029759/how-to-filter-a-gtk-tree-view-that-uses-a-treestore-and-not-a-liststore)
![image](https://user-images.githubusercontent.com/503804/109822590-62595800-7c37-11eb-831c-acfd77220805.png)

I think dconf editor would be a good example: you see a list, typing immediately goes to searching
![image](https://user-images.githubusercontent.com/503804/109822922-ba905a00-7c37-11eb-83e0-cd6bd624f8a9.png)
![image](https://user-images.githubusercontent.com/503804/109822979-c8de7600-7c37-11eb-8b0a-64b7aec867f9.png)

I don't find many wizard-like interfaces. Gnome-DB has an example, but it looks rather dated, and is more used for setting up things, not for regular flows like adding time entries.
![image](https://user-images.githubusercontent.com/503804/109823683-72be0280-7c38-11eb-99b7-353467a942d3.png)

**Comment by frenkel** [comment]
Great, thank you! I'll think about it.

**Comment by frenkel** [comment]
Unfortunately I don't think I can build something like your wireframes or the examples. I'll add it to the feature request list, lets hope somebody else can.
