### ISSUE TITLE
Escape task name text

### ISSUE THREAD

**Issue by wvengen** [frenkel/hfl#37]
When special characters are present in a task name, it can break HTML rendering. E.g. with `Research & development` I see an error message about a misplaced `&`:

> Failed to set text '<b>Project</b> (client)#012Research & development - ' from markup due to error parsing markup: Error on line 2: Entity did not end with a semicolon; most likely you used an ampersand character without intending to start an entity — escape ampersand as &amp;

It looks like the task name could use some html enscaping (and perhaps the project name too, didn't test).

**Comment by frenkel** [comment]
Thanks for reporting this. I’ll fix it this weekend!

**Comment by frenkel** [comment]
This has been fixed in 0.3.6!

**Comment by wvengen** [comment]
Thank you, the problem is indeed fixed :tada:
