### ISSUE TITLE
Compilation instructions for other Linux Distros

### ISSUE THREAD

**Issue by victorandraderam** [frenkel/hfl#38]
Hello

I'm a frequent user of the timer in both Fedora (work) and Ubuntu (home). However, I've recently changed to Manjaro, and I do not know how to proceed to compile the file (I want to avoid the use of alien and other tools to convert deb or rpm)

It is possible to add a short installation description (including dependencies) in the README file?

Warm regards,

**Comment by frenkel** [comment]
Sure, I'll try to add this soon. I have no idea what the package names are, but you need:

- rust (with cargo)
- gtk3 development package

You should then be able to run `cargo run` to build and start a development version. Release version can be build with `cargo build --release`
