### ISSUE TITLE
How do I uninstall this on Fedora?

### ISSUE THREAD

**Issue by gurbaxani** [frenkel/hfl#45]
I installed using the .rpm package. Now it no longer need it. But can not uninstall it because does not appear in my Software center. 

Fedora 35, GNOME

Any help?

**Comment by gurbaxani** [comment]
Figured it out.

`sudo dnf remove timer-for-harvest`

**Comment by frenkel** [comment]
Thanks for documenting this in the README! What made you decide to uninstall the app? What did you not like about it?

**Comment by gurbaxani** [comment]
Hey, you're welcome! Thanks for merging my request.

Nothing wrong with the app. It worked as documented. It just did not have a feature I wanted: Idle detection. For reference, TopTal's [Tracker app](https://www.toptal.com/tracker/) does this flawlessly.

So, I switched to a browser-based web-app.
