### ISSUE TITLE
App won't start at all, seems to crash at start

### ISSUE THREAD

**Issue by jjlankinen** [frenkel/hfl#47]
I've been using this timer-for-harvest for quite a while at it has been working just fine but for some reason it suddenly stopped working. 

App has been granted access to my harvest account.

I'm using Pop_OS 21.04

When trying to run it syslog shows following information (might be something else somewhere but that's all I found fast):

`Mar 21 10:15:14 pop-os timer-for-harvest.desktop[12903]: thread main panicked at 'Port 12345 is already in use: Os { code: 98, kind: AddrInUse, message: "Address already in use" }', src/lib.rs:167:61
Mar 21 10:15:14 pop-os timer-for-harvest.desktop[12903]: note: run with RUST_BACKTRACE=1 environment variable to display a backtrace
Mar 21 10:15:14 pop-os systemd[2947]: app-gnome-timer\x2dfor\x2dharvest-12903.scope: Deactivated successfully.`

Any idea how to remedy this situation?

**Comment by frenkel** [comment]
Some process is listening on port 12345. You will have to stop that before starting. You can find out which one by looking in the last column of the output of this command: `netstat -a -ptn`. Look for a line that mentions ':12345' in the "Local Address" column and then look in the "Program name" column of that line.
